import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";

const ppmori = localfont({
	src: [
		{
			path: "../public/fonts/PPMori.otf",
			weight: "400",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={ppmori.className}>{children}</body>
		</html>
	);
}
